# Generated by Django 2.2.2 on 2020-07-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitanicPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('sibsp', models.IntegerField()),
                ('parch', models.IntegerField()),
                ('fare', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('pclass', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
