# Generated by Django 3.0.7 on 2020-07-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanicprediction',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='titanicprediction',
            name='pclass',
            field=models.IntegerField(choices=[(1, 'Class1'), (2, 'Class2'), (3, 'Class3')]),
        ),
        migrations.AlterField(
            model_name='titanicprediction',
            name='place',
            field=models.CharField(choices=[('queenstown', 'queenstown'), ('southampton', 'southampton'), ('cherbourg', 'cherbourg')], max_length=50),
        ),
    ]
